### ISSUE TITLE
adjusting width of single box

### ISSUE THREAD

**Issue by greenlevel** [ademilter/bricklayer#39]
I just discovered bricklayer and i am happy who it works.

I was just wondering is it possible to make certain boxes wider? e.g. standard box and also column is for example 25%
but i want certain boxes be like 50% while the rest goes around it.
So not that the whole column is 50% width.

Thanks in advance

**Comment by f** [comment]
Hello.

Bricklayer uses CSS to adjusting widths and calculates the size as following:

```scss
@media screen and (min-width: 1200px) {
  .bricklayer-column-sizer {
    /* divide by 3. */
    width: 33.3%;
  }
}

@media screen and (min-width: 768px) {
  .bricklayer-column-sizer {
    /* divide by 2. */
    width: 50%;
  }
}
```

But if you want more dynamic/custom computed layout as you wish, it is not possible.

Thanks
